Fix exception when an user set first or last name with a property
    Uncaught TypeError: val.__proto__.push is not a function
        at eval (eval at v (indexing.js:216), <anonymous>:1:18)
        at v (indexing.js:216)
        at indexing.js:19
        at Array.forEach (<anonymous>)
        at a (indexing.js:7)
        at b.<anonymous> (people.js:462)
        at vuex.esm.js:844
        at vuex.esm.js:466
        at Array.forEach (<anonymous>)
        at vuex.esm.js:465

This exception:
- prevents any user to use Kitsu: the application becomes stuck on the
  'Loading data' message.
- can be triggered using "constructor" or "__proto__".

Unit tests updated, can be executed using:

    npm run test:unit -t tests/unit/lib/indexing.spec.js

Another way to avoid this issue would be to use:

    if (!Object.prototype.hasOwnProperty.call(index, currentString)) {

instead of

    if (index[currentString] === undefined) {

Using simple map seems simpler.